name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.

    container: 
      image: denoland/deno:2.0.0
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: deno install
      
      - name: Publish package to JSR
        run: deno publish